version: '3.3'
services:
  web:
    image: node:9
    container_name: zabori_web
    working_dir: /app
    environment:
      - NODE_ENV=${ENV:-development}
    #build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: bash -c "npm install && npm run ${ENV:-development}"

  api:
    image: node:9
    container_name: zabori_api
    working_dir: /app
    environment:
      - NODE_ENV=${ENV:-development}
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "6000:6000"
    command: bash -c "npm install && npm run ${ENV:-development}"

  nginx:
    container_name: zabori_nginx
    working_dir: /etc/nginx
    build: ./nginx
    ports:
      - "4000:80"
    command: ["nginx", "-g", "daemon off;"]
